version: '3'
services: 

  postgres:
    image: postgres
    environment: 
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: myuser
      POSTGRES_DB: menu
    ports: 
      - "5432:5432"
    volumes: 
      - ./data/ts-test.sql:/docker-entrypoint-initdb.d/ts-test.sql