version: '3'
services: 

  postgres:
    image: postgres
    environment: 
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: test
    ports: 
      - "5432:5432"
    volumes: 
      - ./data/ts-test.sql:/docker-entrypoint-initdb.d/ts-test.sql